name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project
        run: ./gradlew build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: 'https://uploads.github.com/repos/Lyxnx/carcheck_app/releases/29773516/assets{?name,label}'
          asset_path: 'app/build/outputs/apk/debug/app-debug.apk'
          asset_name: 'CarCheck.apk'
          asset_content_type: application/vnd.android.package-archive
